
CONFIG_FILE = "./config.json"

BLACK = (0, 0, 0)
YELLOW = (255, 255, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

WALL_COLOR = BLUE
COIN_COLOR = WHITE
BIGCOIN_COLOR = GREEN
PLAYER_COLOR = YELLOW
GHOST_COLOR = RED

DEFAULT_SIZE = 24


COIN_RESPAWN_TIME = 30  # in sec
COIN_VALUE = 100
BIGCOIN_VALUE = 3000
BIGCOIN_SUMMON_MIN = 15 # in sec
BIGCOIN_SUMMON_MAX = 45 # in sec
BIGCOIN_SIMULTANEOUS_LIMIT = 3


WALL_SYMBOL = "#"
EMPTY_SYMBOL = " "
COIN_SYMBOL = "."
BIGCOIN_SYMBOL = "*"
GHOST_SYMBOL = "!"

AUTO_SAVE_INTERVAL = 1  # in sec
